{% set name = "tzdata" %}
{% set version = "2025.3" %}


package:
  name: python-{{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: de39c2ca5dc7b0344f2eba86f49d614019d29f060fc4ebc8a417896a620b56a7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=40.8.0
    - wheel
  run:
    - python

test:
  source_files:
    - tests
    - VERSION
  imports:
    - tzdata
  requires: 
    - pip
    - pytest
    - pytest-subtests
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/python/tzdata
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://tzdata.readthedocs.io
  dev_url: https://github.com/python/tzdata
  summary: Provider of IANA time zone data
  description: |
    This is a Python package containing zic-compiled binaries for the IANA time zone database.
    It is intended to be a fallback for systems that do not have system time zone data installed (or don't have it installed in a standard location),
    as a part of PEP 615.



extra:
  skip-lints:
    - avoid_noarch
  recipe-maintainers:
    - ocefpaf
    - pganssle
    - mbargull
